// Generated by CoffeeScript 1.9.2
var _ = require("lodash");

module.exports = function removeUnderscoredFiles() {
  return function(files, m, done) {
    _.each(files, function(file, filename) {
      if (_.any(filename.split("/"), function(part) {
        return /^\_/.test(part);
      })) {
        return delete files[filename];
      }
    });
    done();
  };
};
